### PR TITLE
Include serve-static module to make it possible to set the Cache-Cont…

### PR DESCRIPTION
**Pull request by Vispercept**
…rol-Header of static files

### CODE REVIEW

**Comment by Vispercept** [comment]
@marcobullin @matthaias @webmo2001 please review! :smile:

**Comment by marcobullin** [comment]
Approve!

**Comment by Vispercept** [comment]
Integration test.

**Comment by webmo2001** [comment]
approve :-)

**Comment by matthaias** [comment]
#goforit

**Pull request merged**
